### ISSUE TITLE
theme参数无效？

### ISSUE THREAD

**Issue by tonyzzp** [go-xiaohei/pugo#25]
不管theme怎么指定，生成的都是default风格的。

**Comment by fuxiaohei** [comment]
我mac本机执行了

`pugo build --theme="theme/pure"`

可以生成用pure做主题的内容

**Comment by tonyzzp** [comment]
为啥我的不行啊。命令显示是对的，但生成的还是default的。

随便写个theme名，也会提示theme不存在 。

**Comment by fuxiaohei** [comment]
请提供你的平台，PuGo的版本，pugo version可以看到

使用 pugo build --debug，提供更多输出

**Comment by tonyzzp** [comment]
E:\mypugo
λ pugo version
PuGo version 0.10.0 (beta) ~ 2016/04/12 23:24

E:\mypugo
λ pugo build --theme="theme/pure" --debug
INFO|04-12 23:24:53.6146|Build|Start
INFO|04-12 23:24:53.6303|Build|Source|source
DBUG|04-12 23:24:53.6303|Build|Load|source\meta.toml
DBUG|04-12 23:24:53.6303|Build|Load|source\lang\en.toml
DBUG|04-12 23:24:53.6303|Build|Load|source\lang\zh.toml
DBUG|04-12 23:24:53.6303|Build|Load|source\post\2016\first-post.md
DBUG|04-12 23:24:53.6303|Build|Load|source\post\welcome.md
DBUG|04-12 23:24:53.6303|Build|Load|source\page\about.md
DBUG|04-12 23:24:53.6303|Build|Load|source\page\android.md
INFO|04-12 23:24:53.6303|Build|Theme|theme/pure
DBUG|04-12 23:24:53.6529|Build|To|dest/2016/4/12/first-post.html
DBUG|04-12 23:24:53.6529|Build|To|dest/2016/3/25/welcome.html
DBUG|04-12 23:24:53.6529|Build|To|dest/posts/1.html
DBUG|04-12 23:24:53.6529|Build|To|dest/index.html
DBUG|04-12 23:24:53.6529|Build|To|dest/archive.html
DBUG|04-12 23:24:53.6529|Build|To|dest/tags/tag.html
DBUG|04-12 23:24:53.6685|Build|To|dest/tags/pugo.html
DBUG|04-12 23:24:53.6685|Build|To|dest\about.html
DBUG|04-12 23:24:53.6685|Build|To|dest\android.html
DBUG|04-12 23:24:53.6685|Build|To|dest/feed.xml
DBUG|04-12 23:24:53.6685|Build|To|dest/sitemap.xml
DBUG|04-12 23:24:53.6842|Build|Copy|dest\css\blog.css
DBUG|04-12 23:24:53.6842|Build|Copy|dest\css\pure-min.css
DBUG|04-12 23:24:53.6842|Build|Copy|dest\css\railscasts.css
DBUG|04-12 23:24:53.6998|Build|Copy|dest\favicon.ico
DBUG|04-12 23:24:53.7154|Build|Copy|dest\js\highlight.pack.js
DBUG|04-12 23:24:53.7487|Build|Keep|dest\js\jquery-2.1.4.min.js
DBUG|04-12 23:24:53.7502|Build|Keep|dest\robots.txt
DBUG|04-12 23:24:53.7512|Build|Keep|dest\media\author.png
DBUG|04-12 23:24:53.7532|Build|Keep|dest\media\cover.jpg
DBUG|04-12 23:24:53.7532|Build|Keep|dest\media\golang.png
DBUG|04-12 23:24:53.7532|Build|Copy|dest\favicon.ico
DBUG|04-12 23:24:53.7532|Build|Copy|dest\robots.txt
DBUG|04-12 23:24:53.7532|Build|Remove|dest\css\bootstrap.min.css
DBUG|04-12 23:24:53.7532|Build|Remove|dest\css\prism.css
DBUG|04-12 23:24:53.7532|Build|Remove|dest\css\style.css
DBUG|04-12 23:24:53.7532|Build|Remove|dest\js\bootstrap.min.js
DBUG|04-12 23:24:53.7532|Build|Remove|dest\js\prism.min.js
INFO|04-12 23:24:53.7532|Build|11 Pages
INFO|04-12 23:24:53.7532|Build|Done|1|138.5ms

**Comment by fuxiaohei** [comment]
从输出看已经输出了 pure 主题，拷贝的pure-min.css过去，去掉了default主题的bootstrap

**Comment by tonyzzp** [comment]
我发现问题了。

要用go server --static 才可以。
build生成的是对的，但用go server后就变成了default

**Comment by tonyzzp** [comment]
原来server命令也支持--theme参数啊。

**Comment by tonyzzp** [comment]
没看清文档。

**Comment by fuxiaohei** [comment]
应该是我文档写的不清晰，补充一下来
