### ISSUE TITLE
内置服务增加一个md文件编辑功能

### ISSUE THREAD

**Issue by LibiChai** [go-xiaohei/pugo#29]
举例 在启动pugo server 时，访问/admin 可以打开一个编辑页面
该页面会列出source/post文件夹中所有的md文件，点击对应的md文件即可编辑保存
同时增加一个新增按钮，点击后即刻生成一个新的md文件供编写文章保存。
编辑器推荐editor.md提供实时预览功能。

**Comment by fuxiaohei** [comment]
I propose some details:

1. the command `pugo server --admin` to support the feature
2. add `/admin/*` to router for this feature, so I need make the page's url validated
3. the static images can upload and manage in admin panel

**Comment by athurg** [comment]
这个特性目前有眉目了么？
