### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by athurg** [go-xiaohei/pugo#32]
I have about 524 markdown files in post/. When I run `hugo server`, it notice me below:

INFO|09-20 15:48:02.3506|Build|Source|source 
INFO|09-20 15:48:02.4872|Theme|theme/default 
INFO|09-20 15:48:02.5082|Assemble|Done 
INFO|09-20 15:48:03.5709|Done|1349 Pages|1220.5ms 
INFO|09-20 15:48:03.5709|Server|Start|0.0.0.0:9899 
INFO|09-20 15:48:03.5709|Watch|Start 
2016/09/20 15:48:04 http: Accept error: accept tcp [::]:9899: accept: too many open files; retrying in 5ms
2016/09/20 15:48:04 http: Accept error: accept tcp [::]:9899: accept: too many open files; retrying in 10ms
2016/09/20 15:48:04 http: Accept error: accept tcp [::]:9899: accept: too many open files; retrying in 20ms
2016/09/20 15:48:09 http: Accept error: accept tcp [::]:9899: accept: too many open files; retrying in 40ms
2016/09/20 15:48:09 http: Accept error: accept tcp [::]:9899: accept: too many open files; retrying in 80ms
2016/09/20 15:48:09 http: Accept error: accept tcp [::]:9899: accept: too many open files; retrying in 160ms

**Comment by fuxiaohei** [comment]
Is on OSX ?

In `fsnotify`  FAQ, the limit of openning files depends on system,

https://github.com/fsnotify/fsnotify/wiki/FAQ

```
How many files can be watched at once?

There are OS-specific limits as to how many watches can be created:

Linux: /proc/sys/fs/inotify/max_user_watches contains the limit, reaching this limit results in a "no space left on device" error.

BSD / OSX: sysctl variables "kern.maxfiles" and "kern.maxfilesperproc", reaching these limits results in a "too many open files" error.
```

**Comment by fuxiaohei** [comment]
You can use `ulimit` or other ways to change system variables.

I will add `--no-watch` to `server` command. But it can't rebuild after file changes.

**Comment by athurg** [comment]
That's looks work for me. But Instead of change ulimit of system, is there any other better way?

**Comment by fuxiaohei** [comment]
I find a fsevent library without system file handler

https://github.com/radovskyb/watcher

But I think it's not stable now. 

So it seems now alternative way right now.
