### ISSUE TITLE
Embedded theme into pugo

### ISSUE THREAD

**Issue by athurg** [go-xiaohei/pugo#34]
It's better embedded default theme(s) into pugo.  And the path for the project could be only 

.
|- lang/
|- page/
|- post/
`- meta.toml

without the top level 'source', and drop empty path 'dest'

**Comment by fuxiaohei** [comment]
I think it should provide theme files in directory. So that user can modify theme by self.

But the changes of directory structure are great.

```
|- lang
|- page
|- post
|- theme
- meta.toml
```

It seems more clear.

The `dest` need keep exist. I prefer to compile everything into `dest` directory and serve `dest` by http server as static web site.

**Comment by fuxiaohei** [comment]
I move `theme` to `source/theme` in `develop` branch. So all resources are in one folder.

You can use `--from="./"` to make the folder as top level directory, not `source/`.
