### ISSUE TITLE
希望把依赖放到vender里面

### ISSUE THREAD

**Issue by itfanr** [go-xiaohei/pugo#45]
因为众所周知的原因，很多Google的外部库，go get失败。

**Comment by fuxiaohei** [comment]
如果是开发者，这个应该不是问题
如果是使用者，推荐直接使用二进制发布的版本

所以没有必要

**Comment by itfanr** [comment]
@fuxiaohei  O(∩_∩)O哈哈~  有道理

**Comment by itfanr** [comment]
http://fuxiaohei.me/ 

请问这个博客托管在哪里？

我看到https://github.com/fuxiaohei/fuxiaohei-me这个项目好久没更新了。

**Comment by fuxiaohei** [comment]
青云香港

不是天天写文章，当然不是老更新
